In [11]:
# autograd package to do all the computational for us.
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.1342, -0.1606, -0.0178], requires_grad=True)


In [16]:
y = x+2
print(y)
z = y*y*2
# z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([2.1342, 1.8394, 1.9822], grad_fn=<AddBackward0>)
tensor([9.1094, 6.7666, 7.8582], grad_fn=<MulBackward0>)
tensor([3.6992, 9.8100, 2.6509])


In [21]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad()
x.requires_grad_(False)
print(x)

y = x.detach()
print(y)

with torch.no_grad():
  y = x+2
  print(y)

tensor([ 0.1342, -0.1606, -0.0178])
tensor([ 0.1342, -0.1606, -0.0178])
tensor([2.1342, 1.8394, 1.9822])
tensor([2.1342, 1.8394, 1.9822])


In [26]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output= (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
