In [3]:
# Softmax is a mathematical function that converts a vector of raw scores
# (also known as logits) into a probability distribution.
import torch
import torch.nn as nn
import numpy as np

def softmax(x):
  return np.exp(x) / np.sum(np.exp(x), axis =0)

x = np.array([2.0,1.0,0.1])
outputs = softmax(x)
print('softmax numpy:', outputs)

x = torch.tensor([2.0,1.0,0.1])
outputs = torch.softmax(x, dim=0)
print(outputs)

softmax numpy: [0.65900114 0.24243297 0.09856589]
tensor([0.6590, 0.2424, 0.0986])


In [21]:
# Cross-entropy is a measure of the difference between two probability distributions,
# typically used in the context of classification problems.
# same code in numpy

import torch
import torch.nn as nn
import numpy as mp
def cross_entropy(actual, predicted):
  loss = -np.sum(actual * np.log(predicted))
  return loss # /float predicted.shape[0]

# y must be one hot encoded
# if class 0: [1 0 0]
# if class 1: [0 1 0]
# if class 2: [0 0 1]
Y = np.array([1, 0, 0])

# y_pred has probabilities
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)
print(f'Loss1 numpy: {l1:0.4f}')
print(f'Loss2 numpy: {l2:0.4f}')

# ------------------------------------------------------------------------------#---------------------------------------------------------------------------#
# Cross Entropy Loss in Pytorch
import torch
import torch.nn as nn

loss = nn.CrossEntropyLoss()

# # Y contains class indices (not one-hot encoded)
# Y = torch.tensor([0])  # Class index 0

# # Y_pred_good and Y_pred_bad contain logits (raw scores), not probabilities
# Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])  # Raw scores for each class
# Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])     # Raw scores for each class

# 3 samples
Y = torch.tensor([2, 0, 1])

Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])

# Calculate the loss
l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())  # Loss for Y_pred_good
print(l2.item())  # Loss for Y_pred_bad

# Get the predicted classes
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)

print(predictions1)  # Predicted classes for Y_pred_good
print(predictions2)  # Predicted classes for Y_pred_bad

Loss1 numpy: 0.3567
Loss2 numpy: 2.3026
0.3018244206905365
1.6241613626480103
tensor([2, 0, 1])
tensor([0, 2, 1])


In [27]:
# Neural Net With Softmax
import torch
import torch.nn as nn

class NeuralNet2(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super(NeuralNet2, self).__init__()
    self.linear1 = nn.Linear(input_size, hidden_size) # layer
    self.relu = nn.ReLU() # Activation
    self.linear2 = nn.Linear(hidden_size, num_classes) # layer

  def forward(self, x): # forward pass
    out = self.linear1(x)
    out = self.relu(out)
    out = self.linear2(out)
    # no softmax in the end
    return out

model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss() # applies Softmax

In [29]:
# Binary Problems
import torch
import torch.nn as nn

# Binary Classification
class NeuralNet1(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super(NeuralNet1, self).__init__()
    self.linear1 = nn.Linear(input_size, hidden_size) # layer
    self.relu = nn.ReLU() # Activation
    self.linear2 = nn.Linear(hidden_size, num_classes) # layer

  def forward(self, x): # forward pass
    out = self.linear1(x)
    out = self.relu(out)
    out = self.linear2(out)
    # sidmoid in the end
    y_pred = torch.sigmoid(out)
    return y_pred

model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.BCELoss()